// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr7D7QlU2qdDqDv6qpJ-_RoGfJBJesBts',
    appId: '1:934177510759:web:6bfb494853ccd361b84bc2',
    messagingSenderId: '934177510759',
    projectId: 'emuai-ee72a',
    authDomain: 'emuai-ee72a.firebaseapp.com',
    storageBucket: 'emuai-ee72a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3xzR0kzx5opNLnyRJ4yBJt6KcXdjzJA',
    appId: '1:934177510759:android:5634a02a78cda503b84bc2',
    messagingSenderId: '934177510759',
    projectId: 'emuai-ee72a',
    storageBucket: 'emuai-ee72a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4WfS_b2Y6lGG8VufxSE3YNFln2a2WwNU',
    appId: '1:934177510759:ios:b5040cb492e2d53bb84bc2',
    messagingSenderId: '934177510759',
    projectId: 'emuai-ee72a',
    storageBucket: 'emuai-ee72a.firebasestorage.app',
    iosBundleId: 'com.example.emubotFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4WfS_b2Y6lGG8VufxSE3YNFln2a2WwNU',
    appId: '1:934177510759:ios:b5040cb492e2d53bb84bc2',
    messagingSenderId: '934177510759',
    projectId: 'emuai-ee72a',
    storageBucket: 'emuai-ee72a.firebasestorage.app',
    iosBundleId: 'com.example.emubotFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr7D7QlU2qdDqDv6qpJ-_RoGfJBJesBts',
    appId: '1:934177510759:web:03f69a395136df51b84bc2',
    messagingSenderId: '934177510759',
    projectId: 'emuai-ee72a',
    authDomain: 'emuai-ee72a.firebaseapp.com',
    storageBucket: 'emuai-ee72a.firebasestorage.app',
  );

}